site_name: My MKDocs Material Documentation
site_url: https://hackforla.github.io/accessibility/
theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: black

# Repository
repo_name: hackforla/accessibility
repo_url: https://github.com/hackforla/accessibility

