site_name: Hack for LA Accessibility
site_url: https://hackforla.github.io/accessibility/
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

# Repository
repo_name: hackforla/accessibility
repo_url: https://github.com/hackforla/accessibility

